version: "3.8"

services:
  webserver:
    build:
      context: ../client
    container_name: noveltime-webserver
    ports:
      - "80:80"

  was:
    build:
      context: ./
    container_name: noveltime-was
    expose:
      - "8082"

  db:
    image: mariadb:10
    container_name: noveltime-db
    restart: always
    expose:
      - "3306"
    env_file: ./db/.env
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/dump:/disk
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci