version: "3.9"

services:
  noveltime-web:
    build:
      context: ../client
    ports:
      - "8080:80"
      - "8081:443"
      # - "192.168.0.2:8080:80"
    networks:
      - api

  noveltime-was:
    build:
      context: .
    expose:
      - "8082"
    depends_on:
      - noveltime-db
    networks:
      - api
      - db

  noveltime-db:
    image: mariadb:10
    restart: always
    expose:
      - "3306"
    # ports:
    #   - "3306:3306"


    env_file: ./db/.env
    networks:
      - db
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/dump:/disk
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

networks:
  api:
    driver: bridge
  db:
    driver: bridge